// <auto-generated />
namespace WebApplication9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialV9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialV9));
        
        string IMigrationMetadata.Id
        {
            get { return "201701211955084_initialV9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
